### ISSUE TITLE
how do you achieve the synchronization between real bot and bot in gazebo?

### ISSUE THREAD

**Issue by tony9811** [super-owesome/bobble_controllers#14]
the image in your website shows if you hit the real bot,the bot in gazebo shows the same reaction,so could you please tell me how did you do that

**Comment by mike-moore** [comment]
The simulator and associated models were carefully tuned to match real world performance. In addition, the controller and associated gains are identical in simulation as they are on real hardware. You can read more about it here:
https://uhcl-ir.tdl.org/bitstream/handle/10657.1/1416/MOORE-MASTERSTHESIS-2018.pdf?sequence=1&isAllowed=y
