### ISSUE TITLE
Updating ModelState: model [bobblebot] does not exist

### ISSUE THREAD

**Issue by markselias** [super-owesome/bobble_controllers#2]
I followed the installation instructions but ran into the following problem:

> Base path: /home/user/bobble_workspace
> Source space: /home/user/bobble_workspace/src
> Build space: /home/user/bobble_workspace/build
> Devel space: /home/user/bobble_workspace/devel
> Install space: /home/user/bobble_workspace/install
> ####
> #### Running command: "make cmake_check_build_system" in "/home/user/bobble_workspace/build"
> ####
> ####
> #### Running command: "make run_tests_bobble_controllers -j1" in "/home/user/bobble_workspace/build"
> ####
> [ 33%] Built target gtest
> [ 66%] Built target balance_controller_test
> -- run_tests.py: execute commands
>   /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/user/bobble_workspace/src/bobble_controllers --package=bobble_controllers --results-filename test_balance_controller.xml --results-base-dir "/home/user/bobble_workspace/build/test_results" /home/user/bobble_workspace/src/bobble_controllers/test/balance_controller.test 
> ... logging to /home/user/.ros/log/rostest-user-Lenovo-Y50-70-28126.log
> [ROSUNIT] Outputting test results to /home/user/bobble_workspace/build/test_results/bobble_controllers/rostest-test_balance_controller.xml
> [ INFO] [1565709476.487973763]: Subscribing to /bobble/bobble_balance_controller/bb_controller_status
> [INFO] [1565709476.788842, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [ INFO] [1565709477.102629199]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1565709477.103599782]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
> [INFO] [1565709477.174717, 0.000000]: Loading model XML from ros parameter robot_description
> [INFO] [1565709477.178597, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
> [ERROR] [1565709477.871837595, 0.006000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.873605406, 0.008000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.875262115, 0.009000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.877838012, 0.012000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.880885843, 0.014000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.884248511, 0.018000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.886070658, 0.019000000]: Updating ModelState: model [bobblebot] does not exist
> [ INFO] [1565709477.888727992, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
> [ERROR] [1565709477.890309416, 0.023000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.894004270, 0.027000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.897295487, 0.030000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.900844066, 0.033000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.903154240, 0.036000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.905888533, 0.038000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.908063637, 0.040000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.910344974, 0.043000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.912870441, 0.045000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.916279688, 0.048000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.919585573, 0.051000000]: Updating ModelState: model [bobblebot] does not exist
> [ INFO] [1565709477.922360189, 0.054000000]: Physics dynamic reconfigure ready.
> [ERROR] [1565709477.922894625, 0.055000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.924439998, 0.056000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.926108772, 0.058000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.927796207, 0.059000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.930276928, 0.062000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.932191335, 0.064000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.933630357, 0.065000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.934932892, 0.066000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.938926326, 0.070000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.940398535, 0.072000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.943083050, 0.074000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.946175220, 0.077000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.949048362, 0.080000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.951234362, 0.082000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.954391467, 0.085000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.956282847, 0.087000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.959081009, 0.090000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.961161063, 0.092000000]: Updating ModelState: model [bobblebot] does not exist
> [ERROR] [1565709477.964517452, 0.094000000]: Updating ModelState: model [bobblebot] does not exist

I don't have time to debug it now, but I thought I'd let you know.

**Comment by kimcd** [comment]
Were you able to find a resolution?

**Comment by jjholleysoe** [comment]
@kimcd @markselias hey guys!

Sorry for the slow reply on this.  We were relying on git lfs to hold the model, but github has moved to a paid subscription for those services.  This was unknown to us.  I have updated the models to reflect the newest version of bobble-bot and removed lfs - you should be able to get the model if you clone master again.  Please let me know if you have any other issues.

**Comment by jjholleysoe** [comment]
There was also an issue where the model reset was holding bb2 at the origin before the model actually spawned.  This is addressed in the latest hotfix branch I have going if you want to try it out.

**Comment by mike-moore** [comment]
This has been resolved.
