### ISSUE TITLE
RT-Linux distribution

### ISSUE THREAD

**Issue by nameoftherose** [super-owesome/bobble_controllers#3]
Will you please tell me what RT-Linux distribution you are using for the pi with a link if possible.
Thank you

**Comment by jjholleysoe** [comment]
@nameoftherose, I did a post on this a while back for hackaday.  Here is the link:
https://hackaday.io/project/164992-bobble-bot/log/164951-get-realtime

We are hoping to release a SD card image in the future that has this all preloaded to make it easier to use.  Let us know if you are interested!

**Comment by nameoftherose** [comment]
Thank you.Yes I would like to know when the image is released.On Nov 13, 2019 04:31, jjholleysoe <notifications@github.com> wrote:@nameoftherose, I did a post on this a while back for hackaday.  Here is the link:
https://hackaday.io/project/164992-bobble-bot/log/164951-get-realtime
We are hoping to release a SD card image in the future that has this all preloaded to make it easier to use.  Let us know if you are interested!
